#!/usr/bin/env bash
# Bash script that transfers a
# file from our client to a serve.
 
filepath="$1"
ipaddrs="$2"
username="$3"
sshkey_path="$4"

if [ "$#" -lt 3 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$sshkey_path" "$filepath" "$username"@"$ipaddrs":~/
fi
