#!/usr/bin/env bash
# redicts to another url

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
sudo service nginx start

sudo chown -R $USER:$USER /var/www/html
sudo chown -R $USER:$USER /etc/nginx/sites-available

echo "Hello World!" > /var/www/html/index.html
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "37i\ $redirect" /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
err_page="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $err_page" /etc/nginx/sites-available/default

sudo sed -i '/# First attempt to serve request as file, then/a \\t\tadd_header X-Served-By hostname;' /etc/nginx/sites-available/default

sudo service nginx restart
sudo service nginx reload

